### ISSUE TITLE
Adding chrome-extension-reload triggers infinity loop on watch task

### ISSUE THREAD

**Issue by daniula** [freedomflyer/grunt-chrome-extension-reload#4]
Grunt works fine with config like this (made it just for test):

```
watch: {
    js: {
        files: ['**/*.js'],
        tasks: ['notify:extension'],
    },
},
notify: {
    extension: { options: { message: 'Extension reloaded' } },
}
```

At the end of Gruntfile I load and register my tasks:

```
grunt.loadNpmTasks('grunt-contrib-compress');
grunt.loadNpmTasks('grunt-webstore-upload');
grunt.loadNpmTasks('grunt-contrib-watch');
grunt.loadNpmTasks('grunt-notify');

grunt.registerTask('deploy', ['compress', 'webstore_upload']);
```

However, as soon as I add `grunt.loadNpmTasks('grunt-chrome-extension-reload');` calling `grunt watch` triggers infinity loop:

```
Running "watch" task
Waiting...
Verifying property watch exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch" missing.

Running "watch" task
Waiting...
Verifying property watch exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch" missing.

Running "watch" task
Waiting...
Verifying property watch exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch" missing.
```

**Comment by ddehghan** [comment]
Same here. :-(

...  back to ^R  :-(

**Comment by daniula** [comment]
@ddehghan I started writing my short bash script which use `chrome-cli` to do the same thing as this grunt task but there are lots of small issues to pull it together and make it work. I'll try to post it here if I manage to make it work.

**Comment by ddehghan** [comment]
That would be great. :)  Are the content script files reloaded by just
refreshing the chrome://extensions page?

I always click on reload button for the specific extension manually.

**Comment by daniula** [comment]
I was still testing that. I figured out that extension is not reloading when developer tools inspecting background page are opened and another case when user don't have `chrome://extensions/` tab opened.

It's not so trivial task. Hopefully this extension has this things covered, will get fixed and work soon.

**Comment by ddehghan** [comment]
awesome. ;-)

**Comment by joelworsham** [comment]
Same here. Author where are you?

**Comment by freedomflyer** [comment]
Hey guys. I'm here and open for PRs :)
